name: Deploy program to mainnet

inputs:
  rpc:
    description: 'rpc'
    required: true
    type: string
  pid:
    description: 'program PID'
    required: true
    type: string
  pid_env_var:
    description: 'program PID env var'
    required: true
    type: string
  program_name:
    description: 'program name'
    required: true
    type: string
  program_index:
    description: 'program index in Squads'
    required: true
    type: string
  kp:
    description: 'Deploy KP'
    required: true
    type: string
  ssh_private_key:
    description: 'SSH private key'
    required: true
    type: string
  multisig_auth:
    description: 'Multisig Auth Pubkey'
    required: true
    type: string
  multisig_pda:
    description: 'Multisig PDA Pubkey'
    required: true
    type: string
  buffer_key:
    description: 'Program buffer key'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Setup program
      uses: bridgesplit/anchor-setup-gh-action@v1.0.8
      with:
        ssh_private_key: ${{ inputs.ssh_private_key }}
        rpc: ${{ inputs.rpc }}
        pid: ${{ inputs.pid }}
        pid_env_var: ${{ inputs.pid_env_var }}

    - run: solana-keygen new -o buffer-keypair --no-bip39-passphrase
      name: Gen Buffer KP
      shell: bash
    - run: echo "$KEYPAIR" > ./deploy-keypair.json && chmod 600 ./deploy-keypair.json
      name: Set Deploy KP
      shell: bash
      env:
        KEYPAIR: ${{ inputs.kp }}
    - run: solana program close --buffers -k ./deploy-keypair.json
      name: Close old buffers
      shell: bash
      env:
        KEYPAIR: ${{ inputs.kp }}
  
    - name: Buffer Deploy
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 30
        max_attempts: 10
        shell: bash
        command: solana program write-buffer --buffer ./buffer-keypair -k ./deploy-keypair.json ./target/deploy/$PROGRAM.so -u $NETWORK > ./buffer.out
      env:
        NETWORK: ${{ inputs.rpc }}
        PROGRAM: ${{ inputs.program_name }}

    - name: Set buffer output
      id: buffer-deploy
      shell: bash
      run: |
        echo "buffer=$(cat buffer.out | sed 's/Buffer: //g' | xargs echo -n)" >> $GITHUB_OUTPUT
    - run: echo "buffer=${{ steps.buffer-deploy.outputs.buffer }}"
      shell: bash
      
    - name: Transfer buffer to authority
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 10
        shell: bash
        command: solana program set-buffer-authority $BUFFER -k ./deploy-keypair.json --new-buffer-authority $AUTHORITY -u $NETWORK
      env:
        BUFFER: ${{ steps.buffer-deploy.outputs.buffer }}
        AUTHORITY: ${{ inputs.multisig_auth }}
        NETWORK: ${{ inputs.rpc }}

    - run: rm ./deploy-keypair.json
      shell: bash
    
    - name: Squads Program Upgrade
      uses: bridgesplit/squads-program-upgrade@v1.0.0
      with:
        network-url: ${{ inputs.rpc }}
        program-multisig: ${{ inputs.multisig_pda }}
        program-id: ${{ inputs.pid }}
        program-index: ${{ inputs.program_index }}
        buffer: ${{ steps.buffer-deploy.outputs.buffer }}
        spill-address: ${{ inputs.multisig_auth }}
        authority: ${{ inputs.multisig_auth }}
        name: 'Multisig GH Deploy'
        keypair: ${{ inputs.kp }}
